# Generated by Django 4.2 on 2026-03-06 05:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'location_location',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rows', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_per_row', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.location')),
            ],
            options={
                'db_table': 'cinemas_cinema',
            },
        ),
        migrations.AlterModelTable(
            name='cinema',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cinema',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinemas', to='cinemas.location'),
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_cinema_per_location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country', 'state', 'city', 'area'), name='unique_location'),
        ),
        migrations.AddField(
            model_name='seat',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinemas.cinema'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('cinema', 'row_number', 'seat_number'), name='unique_seat_per_cinema'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
